export type Role =
  | "SalesManager"
  | "Admin"
  | "Receptionist"
  | "Executive"
  | "GeneralManager"
  | "Accountant"
  | "FinanceDirector"
  | "FinanceManager"
  | "FinanceAssistant"
  | "MakeReady"
  | "SalesPerson"
  | "DealLog"
  | "StatusLog"
